web:
  image: wordpress:4.9.8-php7.0-apache
  links:
  - mysql
  environment:
  - WORDPRESS_DB_PASSWORD=12345
  ports:
  - "8080:80"
  volumes:
  - /Users/nthings/Documents/Projects/qi-theme/:/var/www/html/wp-content/themes/qi-theme
  - /Users/nthings/Documents/Projects/cesqt-qi/:/var/www/html/wp-content/plugins/cest-qi
  - /Users/nthings/Documents/Projects/expedientes-qi/:/var/www/html/wp-content/plugins/expedientes-qi
  - /Users/nthings/Documents/Projects/resiliencia-qi/:/var/www/html/wp-content/plugins/resiliencia-qi
  - /Users/nthings/Documents/Projects/areasorg-qi/:/var/www/html/wp-content/plugins/areasorg-qi
mysql:
  image: mysql:5.7
  environment:
  - MYSQL_ROOT_PASSWORD=12345
  - MYSQL_DATABASE=wordpress
  ports:
  - 3306:3306